freebsd_instance:
  image_family: freebsd-14-0

task:
  name: "Build"
  install_script: >
    pkg install -y cmake ninja
    graphics/png graphics/webp graphics/tiff graphics/libheif graphics/libavif
    graphics/libimagequant print/freetype2 x11-fonts/fontconfig print/libraqm
  script: |
      mkdir build
      cd build
      cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
      ninja
