freebsd_instance:
  image_family: freebsd-14-0

task:
  name: "Build"
  install_script: >
    pkg install -y cmake ninja pkgconf
    graphics/png graphics/webp graphics/tiff graphics/libavif
    graphics/libimagequant print/freetype2 x11-fonts/fontconfig print/libraqm
  script: |
      mkdir build
      cd build
      cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug \
      -DENABLE_PNG=1 -DENABLE_FREETYPE=1 -DENABLE_JPEG=1 -DENABLE_WEBP=1 \
      -DENABLE_TIFF=1 -DENABLE_XPM=1 -DENABLE_GD_FORMATS=1 \
      -DENABLE_RAQM=1 -DENABLE_AVIF=1 -DBUILD_TEST=1
      ninja
